---
server:
  port: 8761


spring:
  profiles: vs1
  application:
    name: eureka-vs1
  
eureka:
  instance:
    hostname: vs1
  client:
    registerWithEureka: false
    fetchRegistry: false
    defaultZone: http://vs2:8762/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 800000
    
#logging:
#  level:
#    com.netflix: DEBUG
    
---
server:
  port: 8762


spring:
  profiles: vs2
  application:
    name: eureka-vs2
  
eureka:
  instance:
    hostname: vs2
  client:
    registerWithEureka: false
    fetchRegistry: false
    defaultZone: http://vs1:8761/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 800000 #dev
    
#logging:
#  level:
#    com.netflix: DEBUG
   