---
server:
  port: 8090
 
spring:
  application:
    name: miaosha-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://vs1:8761/eureka,http://vs2:8762/eureka
        
default:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  client:
    config:
      defult:
        connectTimeout: 10000
        readTimeout: 12000
  hystrix:
    enabled: true
    
#logging:
#  level:
#    com.netflix: DEBUG

    